### Fluxos de email

### Solicitar criacao de conta
POST http://localhost:4500/usuarios/solicitar-criacao
Content-Type: application/json

{
  "nome": "Joao Silva",
  "email": "joao.silva@example.com",
  "senha": "senha123"
}

### Solicitar exclusao de conta
POST http://localhost:4500/usuarios/solicitar-exclusao
Content-Type: application/json

{
  "nome": "Joao Silva",
  "email": "joao.silva@example.com",
  "senha": "senha123"
}

### Criar codigo de recuperacao de senha
POST http://localhost:4500/usuarios/criar-codigo-verificacao
Content-Type: application/json

{
  "email": "joao.silva@example.com"
}

### Atualizar senha com codigo
POST http://localhost:4500/usuarios/atualizar-senha
Content-Type: application/json

{
  "email": "joao.silva@example.com",
  "codigo": "123456",
  "novaSenha": "novaSenha123"
}
