### API de perfis padrao

### Listar perfis padrao
GET http://localhost:4500/padrao

### Obter perfil padrao por usuario
GET http://localhost:4500/padrao/3

### Criar perfil padrao
POST http://localhost:4500/padrao/3
Content-Type: application/json

{
  "profissao": "Ilustrador",
  "nome_de_usuario": "joao.silva",
  "descricao": "Perfil padrao de teste",
  "certificados": "Certificado de Ilustracao"
}

### Atualizar perfil padrao
PUT http://localhost:4500/padrao/3
Content-Type: application/json

{
  "profissao": "Designer",
  "nome_de_usuario": "joao.designer",
  "descricao": "Perfil padrao atualizado",
  "certificados": "Certificado de Design"
}

### Excluir perfil padrao
DELETE http://localhost:4500/padrao/3
